### ISSUE TITLE
Re-running notebooks

### ISSUE THREAD

**Issue by NoraLoose** [miniufo/xinvert#24]
When trying to re-run the notebooks, three of them fail:

- [x] In `11_Omega_equation.ipynb` the following fails because the netcdf file is not available
```
ds = xr.open_dataset('I:/Omega/OFES30_20011206_Qian/data.nc',
                     chunks={'lev':6}).astype('f4')
```

- [x] In `04_Eliassen_model.ipynb` the following fails:
```
ds = xr.open_dataset('../../../Data/Zonalmean.nc')
```
The latter is simply a typo in the filename; it needs to be changed to `./../../Data/ZonalMean.nc`

- [x] In `test_01_Stommel_Arons_model.ipynb` the following fails:
```
eps = xr.where(basin, eps, np.nan)
```
with the error
```
ValueError: cannot align objects with join='exact' where index/labels/sizes are not equal along these coordinates (dimensions): 'lon' ('lon',)
```

This is part of the review process at https://github.com/openjournals/joss-reviews/issues/5510.

**Comment by miniufo** [comment]
Hi @NoraLoose thanks for your careful check.

>  In `11_Omega_equation.ipynb` the following fails because the netcdf file is not available

This notebook contains two examples.  The first one in the atmospheric context should be OK.  The second one use a large oceanic dataset (> 1GB) that cannot be uploaded to github (a 3D case).  It is not easy to reproduce the result by others because of this limit.  I put it here because I may sometimes check it myself, and I could also easily turn all the notebooks into docs.  Since data size cannot be reduced any further, I just don't know how to fix this.  Do you have any suggestion?

> In `04_Eliassen_model.ipynb` the following fails:

This can be fixed easily.

> In `test_01_Stommel_Arons_model.ipynb` the following fails:

All the notebooks start with `test` rather than a number are actually not ready for others to run.  So I guess I may move them to another place.  Only when they are ready, should I move them back here (I may need to modifiy the relative paths).

**Comment by miniufo** [comment]
Hi @NoraLoose, I've:
- fixed the large-file issue in omega example using `pooch`;
- fixed the filename in Eliassen example;
- move all the unfinished notebooks somewhere else.

Please check these again.  Thanks very much for the suggestions on solving these issues.
