### ISSUE TITLE
Diabatic Forcing term in QG Omega

### ISSUE THREAD

**Issue by ngyawali** [miniufo/xinvert#8]
The Q-vector form of the Omega equation doesn't have an adiabatic forcing term in your calculation. Is there any easy way to incorporate that term while calculating the Omega value from the Qvector form of the Omega equation?

**Comment by miniufo** [comment]
The main task for this package is to do the inversion once the forcing is provided or prescribed.  So if you mean diabatic forcing in the atmosphere, such as latent heating $Ldq/dt$ where $q$ is specific humidity, you can do the calculation yourself or get it from model outputs.  The calculation of the forcings are not the primary target for this package, because there are many different forcings for different problems.  It is not easy to take all of them into account.

But there is a `FiniteDiff` module that allows you to do the finite difference of a DataArray.  You may figure out how to calculate your forcing using this module.

**Comment by miniufo** [comment]
Close this now and feel free to re-open it in any case.
